### ISSUE TITLE
License file in repo & npm package

### ISSUE THREAD

**Issue by dariagrudzien** [sindresorhus/callsites#6]
@sindresorhus Hi Sindre, thank you for this package. Would you mind adding the license file to the npm package of v0.2.0 and latest? Without it we're not really able to use it, because it makes the npm package a distribution of proprietary code.

Additionally I noticed the license file does not include the date, which makes it invalid. I'd greatly appreciate it if you could add the dates to the license files in GH repo as well.

Many thanks for your consideration.

**Comment by sindresorhus** [comment]
Same answer as https://github.com/sindresorhus/is-path-cwd/issues/5#issuecomment-435030426.

**Comment by patricksmms** [comment]
@sindresorhus, same here, it's your own `caller-path@0.1.0` that is included by `require-uncached@1.0.3` that includes this.

**Comment by patricksmms** [comment]
@sindresorhus, we would really appreciate if you coud publish `require-uncached@1.0.4` from the latest code on the repo. It would get the license issue cleared out of `caller-path` and `callsites`.
